# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_date',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.CharField(max_length=20),
        ),
    ]
