# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbapp', '0003_auto_20161217_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default=91, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='seller_name',
            field=models.CharField(default=91, max_length=100),
            preserve_default=False,
        ),
    ]
